Repository EntryDSM/Rolls-Royce, pull requests merged in 2021-12, with the labels that each got.

#271 🔀 :: (#270) Birthday Format
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
Labels: 버그

#273 🔀 :: (#272) 사진 저장
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/UploadPhotoService.java
Labels: 버그

#275 🔀 :: (#274) Type 변경 NPE
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeTypeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
Labels: 버그

#277 🔀 :: (#276) Type 변경 정보 추가
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/domain/Graduation.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/domain/Qualification.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/request/ChangeTypeRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeTypeService.java
Labels: 버그, 기능 추가

#279 🔀 :: 지원자 목록 400, 500 수정
  build.gradle
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/GetApplicantsRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantsService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/domain/Graduation.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/status/domain/Status.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserInformationRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserInformationRepositoryImpl.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/config/QueryDslConfig.java
Labels: 버그

#281 🔀 :: (#280) @RequestController 사용 오류 수정
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/exception/AdminNotAccessibleException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/AdminController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/ApplicantController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/ApplicationController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/ApplicationCountController.java
Labels: 버그

#284 🔀 :: (#283) 검정고시 정보입력 500
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/Score.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/facade/ScoreFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/service/UpdateGraduationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/service/UpdateQualificationService.java
Labels: 버그

#287 🔀 :: (#286) 졸업자 / 미졸업자 정보입력 정책변경
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/presentation/dto/request/UpdateGraduationRequest.java
Labels: chore

#285 🔀 :: (#282) Application TABLE_PER_CLASS 제거
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/ApplicationCase.java
Labels: 리팩토링

#290 🔀 :: (#289) equals NPE
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/facade/AdminFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/AdmissionTicketExcelService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantDetailsService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/domain/Graduation.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeTypeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/FinalSubmitService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/GraduationCase.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
Labels: 버그

#294 🔀 :: (#293) S3 Object링크 가져오기
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/s3/S3Util.java
  src/main/resources/application.yml
Labels: 버그

#292 🔀 :: (#291) Score 도메인 PrimaryKeyJoinColumn 제거
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/Score.java
Labels: 리팩토링

#296 🔀 :: (#295) Tmap api 전송 제한 및 수험표 출력 로직 최적화
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/AdmissionTicketExcelService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeInformationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/dto/UpdateUserInformationDto.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
Labels: 버그, 리팩토링

#299 🔀 :: 일정 수정 NPE 예외 처리
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/exception/InvalidScheduleRequestException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/presentation/ScheduleController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/service/UpdateSchedulesService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
Labels: 버그

#300 🔀 :: (#298) null인지를 검사
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/service/UpdateSchedulesService.java
Labels: 버그

#303 🔀 :: (#302) ChangeStudyPlanService Transactional 어노테이션 추가
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeStudyPlanService.java
Labels: 버그, 리팩토링

#305 🔀 :: (#304) 최종제출 중복 체크
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/FinalSubmitService.java
Labels: 버그

#307 🔀 :: (#306) 성별 잘못된 값
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
Labels: 버그

#311 🔀 :: (#310) Cors 설정
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/WebConfig.java
Labels: 프로젝트 설정

#309 🔀 :: (#308) admin & schedule dto 생성자 설정 변경
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/ChangeApplicationCountRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/CheckPasswordRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/LoginRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/response/ApplicantDetailsResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/response/ApplicantsResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantDetailsService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/presentation/dto/request/ScheduleRequest.java
Labels: 리팩토링

#315 🔀 :: (#314) User Service 코드 정리
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/ChangePasswordService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserSignupService.java
Labels: 리팩토링

#313 🔀 :: (#312) Application Service 코드 정리
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/facade/ApplicationFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeGraduationInformationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeInformationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeTypeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/FinalSubmitService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/QueryGraduationInformationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/QueryInformationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/QueryIntroduceService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/QueryStudyPlanService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/QueryTypeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/ApplicationPdfService.java
Labels: 리팩토링

#317 🔀 :: (#316) Score Facade 코드 정리
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/facade/ScoreFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/service/UpdateGraduationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/service/UpdateQualificationService.java
Labels: 리팩토링

#319 🔀 :: (#318) isNotSubmitted 추가 및 카멜케이스 요청으로 변경
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/AdminController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/GetApplicantsRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantsService.java
Labels: chore

#321 🔀 :: 원서 도착 여부 쿼리 파라미터 받은 걸로 status 값 수정하기
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/ApplicationController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/UpdateIsPrintsArrivedService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/status/domain/Status.java
Labels: chore

#323 🔀 :: (#322) 쿼리파라미터, 목록 dto, 상세 dto 변수명 통일시키기 is_prints_arrived
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/ApplicationController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/response/ApplicantDetailsResponse.java
Labels: chore
