Repository EntryDSM/Rolls-Royce, pull requests merged in 2021-11, with the labels that each got.

#157 🔀 :: (#137) Image Util
  build.gradle
  src/main/java/kr/hs/entrydsm/rollsroyce/global/exception/BadFileExtensionException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/exception/FileIsEmptyException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/exception/ImageNotFoundException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/s3/S3Util.java
  src/main/resources/application.yml
Labels: 기능 추가

#159 🔀 :: (#158) Aop 오류 수정
  src/main/java/kr/hs/entrydsm/rollsroyce/global/aop/SubmitAspect.java
Labels: 버그

#168 🔀 :: (#166) Aws starter WARN 메시지 제거
  src/main/resources/application.yml
Labels: chore

#156 🔀 :: (#151) 미졸업자/졸업자 정보 조회
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/domain/repository/GraduationRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/GraduationCaseRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/QualificationCaseRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/ScoreRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/exception/GradeNotFoundException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/presentation/ScoreController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/presentation/dto/response/QueryGraduationResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/service/QueryGraduationService.java
Labels: 기능 추가

#165 🔀 :: (#164) Pageable 예외 핸들링
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/GlobalExceptionHandler.java
Labels: 버그, chore, 프로젝트 설정

#169 🔀 :: (#160) 검정고시 정보 조회
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/QualificationCaseRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/presentation/ScoreController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/presentation/dto/response/QueryGraduationResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/presentation/dto/response/QueryQualificationExamResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/service/QueryQualificationExamService.java
Labels: 기능 추가

#167 🔀 :: (#161) 이미지 등록 Api
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/ApplicationUserController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/UploadPhotoService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
Labels: 기능 추가

#176 🔀 :: (#161) 이미지 등록 Api
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/ApplicationUserController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/UploadPhotoService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
Labels: 기능 추가

#173 🔀 :: (#172) 유저랑 스코어 매핑
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
Labels: chore

#136 🔀 :: (#121) 지원자 상세보기
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/AdminController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/response/ApplicantDetailsResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantDetailsService.java
Labels: 기능 추가

#178 🔀 :: (#171) 유저 회원가입
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/request/SignupRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserLoginService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserSignupService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
Labels: 버그

#181 🔀 :: (#174) getCurrentUser로 변경
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeGraduationInformationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeInformationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeIntroduceService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeStudyPlanService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeTypeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/FinalSubmitService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/QueryGraduationInformationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/QueryInformationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/QueryIntroduceService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/QueryStudyPlanService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/QueryTypeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/UploadPhotoService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/Score.java
Labels: 리팩토링

#186 🔀 :: (#183) Exception 생성자 접근제한자
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/exception/AdminNotAccessibleException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/exception/AdminNotFoundException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/exception/ExcelOException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/exception/InvalidKeywordException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/exception/PasswordNotValidException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/GetApplicantsRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/CheckPasswordService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/exception/ScheduleNotFoundException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/school/exception/SchoolNotFoundException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/exception/FieldNotExistException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/exception/GradeNotFoundException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/exception/GradeOrScoreNotFoundException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/status/exception/AlreadySubmitException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/status/exception/StatusNotFoundException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/exception/ApplicationNotFoundException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/exception/AuthCodeAlreadyVerifiedException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/exception/AuthCodeRequestOverLimitException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/exception/CredentialsNotFoundException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/exception/InvalidAuthCodeException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/exception/InvalidEnumConstantException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/exception/UnprovenAuthCodeException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/exception/UserAlreadyExistsException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/exception/UserNotFoundException.java
Labels: 버그, 리팩토링

#184 🔀 :: (#152) 미졸업자/졸업자 정보 입력 api
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/ApplicationCase.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/GraduationCase.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/QualificationCase.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/Scorer.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/exception/ApplicationTypeUnmatchedException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/presentation/ScoreController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/presentation/dto/request/UpdateGraduationRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/service/UpdateGraduationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
Labels: 기능 추가, 리팩토링

#192 🔀 :: (#191) CD 구축
  .github/workflows/CD.yml
Labels: 프로젝트 설정

#197 🔀 :: (#196) CD 오류 해결
  .github/workflows/CD.yml
Labels: 버그

#195 🔀 :: (#194) PDF Util 생성
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/domain/Graduation.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/config/Font.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/exception/EducationalStatusNullException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/exception/FinalSubmitRequiredException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/exception/ScoreNotFoundException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/ApplicationPdfGenerator.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/ConverterPropertiesCreator.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/EducationalStatus.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/PdfData.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/PdfDataConverter.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/PdfProcessor.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/TemplateFileName.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/TemplateProcessor.java
  src/main/resources/templates/admission_agreement.html
  src/main/resources/templates/application_for_admission.html
  src/main/resources/templates/introduction.html
  src/main/resources/templates/nonsmoking.html
  src/main/resources/templates/recommendation.html
Labels: 기능 추가, 프로젝트 설정

#201 🔀 :: (#200) Dockerfile 생성
  Dockerfile
Labels: 프로젝트 설정

#199 🔀 :: (#198) 원서 Pdf 출력 Api
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/ApplicationPdfController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/ApplicationPdfService.java
Labels: 기능 추가

#202 🔀 :: (#200) Dockerfile 생성
  Dockerfile
Labels: 버그

#203 🔀 :: (#200) Dockerfile 생성
  Dockerfile
Labels: 버그

#205 🔀 :: (#204) 배포 버그 정리
  .github/workflows/CD.yml
  build.gradle
Labels: 버그

#188 🔀 :: (#187) 유저 토큰 재발급
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendAuthCodeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserSignupService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserTokenRefreshService.java
Labels: 기능 추가

#206 🔀 :: 수험표 출력 세팅
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/exception/ApplicationPeriodNotOverException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/AdmissionTicketExcelService.java
Labels: 프로젝트 설정

#208 🔀 :: 어드민 리팩토링
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/facade/AdminAuthenticationFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/facade/AdminFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/AdminController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/ApplicantController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/ApplicationController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/AuthController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/ExcelController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/LoginRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/AdmissionTicketExcelService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/CancelApplicationSubmitService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/CheckPasswordService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/DeleteAllTablesService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantDetailsService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantsService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/UpdateApplicantIsPaidService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/UpdateIsPrintsArrivedService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/service/UpdateSchedulesService.java
Labels: 리팩토링

#210 🔀 :: (#209) Schedule Facade
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/AdmissionTicketExcelService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/DeleteAllTablesService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/domain/Schedule.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/domain/repository/ScheduleRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/facade/ScheduleFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/service/GetSchedulesService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/service/UpdateSchedulesService.java
Labels: 기능 추가, 프로젝트 설정

#217 🔀 :: (#216) 권한 설정
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
Labels: 버그

#219 🔀 :: (#218) 이메일 인증
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendAuthCodeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/exception/MessageRejectedException.java
Labels: 버그

#213 🔀 :: (#212) 복잡한 파라미터 빌더로 정리
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeInformationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/dto/UpdateUserInformationDto.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
Labels: 리팩토링

#211 🔀 :: (#193) 일정 체크
  src/main/java/kr/hs/entrydsm/rollsroyce/global/aop/RollsAspect.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/exception/InvalidDateException.java
Labels: 기능 추가

#215 🔀 :: (#214) 디미터 법칙 준수
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeGraduationInformationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/FinalSubmitService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
Labels: 리팩토링

#221 🔀 :: (#220) Api permission 설정
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
Labels: 프로젝트 설정

#223 🔀 :: (#222) ApplicationCount Entity
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/domain/ApplicationCount.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/domain/repository/ApplicationCountRepository.java
Labels: 기능 추가, 프로젝트 설정

#224 🔀 :: (#123) 수험표 출력
  build.gradle
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/exception/ApplicationCountNotFoundException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/exception/InvalidFileException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/facade/ApplicationCountFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/ExcelController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/AdmissionTicketExcelService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/domain/Application.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/domain/Graduation.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/domain/Qualification.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/facade/ScoreFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/status/domain/Status.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/status/domain/facade/StatusFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/status/domain/repository/StatusRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/types/ApplicationType.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/exception/RequestFailToOtherServerException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/openfeign/apis/FeignClientErrorDecoder.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/openfeign/apis/FeignConfiguration.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/openfeign/apis/client/TmapApi.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/openfeign/apis/dto/request/RouteRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/openfeign/apis/dto/response/CoordinateResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/openfeign/apis/dto/response/RouteResponse.java
  src/main/resources/application.yml
Labels: 기능 추가

#226 🔀 :: (#255) User의 OneToOne관계 제거 및 버그 해결
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/excel/AdmissionTicket.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/excel/ApplicantInformation.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/AdmissionTicketExcelService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/CancelApplicationSubmitService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/DeleteAllTablesService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantDetailsService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantsService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/UpdateIsPrintsArrivedService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/domain/Graduation.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/facade/ApplicationFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/request/ChangeGraduationInformationRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/response/QueryGraduationInformationResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeGraduationInformationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeTypeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/FinalSubmitService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/QueryGraduationInformationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/QueryTypeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/ScoreRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/facade/ScoreFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/status/domain/Status.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/status/domain/facade/StatusFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserInformationRepositoryImpl.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/openfeign/apis/client/TmapApi.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/openfeign/apis/dto/request/RouteRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/openfeign/apis/dto/response/CoordinateResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/openfeign/apis/dto/response/RouteResponse.java
Labels: 버그, 리팩토링

#231 🔀 :: (#230) 이메일 인증 코드 전송
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/AuthCode.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/AuthCodeLimit.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendAuthCodeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserSignupService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/ses/SESUtil.java
  src/main/resources/application.yml
Labels: 버그, 리팩토링

#233 🔀 :: (#232) @Value 오류
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendAuthCodeService.java
Labels: 버그

#229 🔀 :: (#228) 접수 현황 집계(점수)
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/AdminController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/response/CommonScoreResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/response/SpecialScoreResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/response/StaticsScoreResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/QueryStaticsScore.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/types/ApplicationType.java
Labels: 기능 추가

#227 🔀 :: (#122) 접수 현황 집계(지원자)
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/AdminController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/response/StaticsCountResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/AdmissionTicketExcelService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/QueryStaticsCountService.java
Labels: 기능 추가

#235 🔀 :: (#234) CORS 허용 Origin 추가
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/WebConfig.java
Labels: chore

#237 🔀 :: (#236) json 형태는 snake_case로 주고받을 수 있게끔
  src/main/resources/application.yml
Labels: 버그

#239 🔀 :: (#238) SES 템플릿 변경
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendAuthCodeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/ses/SESUtil.java
Labels: 버그

#244 🔀 :: (#243) 로깅 구축
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/logging/LogWriter.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/logging/RequestLogger.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/logging/RequestWrapper.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/ConverterPropertiesCreator.java
  src/main/resources/application.yml
Labels: 기능 추가, 프로젝트 설정

#246 🔀 :: (#245) yml 형식 통일
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/s3/S3Util.java
  src/main/resources/application.yml
Labels: chore

#248 🔀 :: (#247) AWS_S3_URL
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/s3/S3Util.java
Labels: chore

#251 🔀 :: (#249) 유형별 인원 가져오기 Api
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/domain/repository/ApplicationCountRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/ApplicationCountController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/response/QueryApplicationCountResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/QueryApplicationCountService.java
Labels: 기능 추가

#254 🔀 :: (#253) 비밀번호 인증 번호 전송 컨트롤러
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendEmailAuthCodeService.java
Labels: 버그, 기능 추가

#252 🔀 :: (#250) 유형별 인원 변경 Api
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/domain/ApplicationCount.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/ApplicationCountController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/ChangeApplicationCountRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ChangeApplicationCountService.java
Labels: 기능 추가

#257 🔀 :: (#256) map 내부 save 적용 오류
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/ChangePasswordService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendEmailAuthCodeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendPasswordAuthCodeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/VerifyAuthCodeService.java
Labels: 버그

#259 🔀 :: (#258) Status save not null
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserSignupService.java
Labels: 버그

#263 🔀 :: (#262) EducationalStatus NPE
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/QueryTypeService.java
Labels: 버그

#265 🔀 :: (#264) getCurrentUser 영속성 콘텍스트
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/request/ChangeTypeRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeGraduationInformationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeInformationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeIntroduceService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeTypeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/FinalSubmitService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/auth/AuthDetails.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/auth/AuthDetailsService.java
Labels: 버그

#267 🔀 :: (#266) Application 없어도 Type 가능하게
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/facade/ApplicationFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/QueryTypeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
Labels: 버그

#269 🔀 :: (#268) 버그 해결
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/request/ChangeInformationRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/response/QueryGraduationInformationResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/response/QueryInformationResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeInformationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeTypeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/QueryGraduationInformationService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/dto/UpdateUserInformationDto.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/PdfData.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/PdfDataConverter.java
Labels: 버그
