Repository EntryDSM/Rolls-Royce, pull requests merged in 2021-10, with the labels that each got.

#126 🔀 :: (#116) 이메일 인증코드 확인 API
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/exception/AuthCodeAlreadyVerifiedException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/exception/InvalidAuthCodeException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/request/VerifyAuthCodeRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/VerifyAuthCodeService.java
Labels: 기능 추가

#127 🔀 :: (#112)지원자 목록
  build.gradle
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/exception/InvalidKeywordException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/AdminController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/GetApplicantsRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/response/ApplicantsResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantsService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/domain/Graduation.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/status/domain/Status.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserCustomRepository.java
Labels: 기능 추가, chore

#128 🔀 :: (#124) 유저 로그인 API
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/request/LoginRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserLoginService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserSignupService.java
Labels: 기능 추가, 리팩토링

#133 🔀 :: (#129) 유저 상태 조회
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/status/domain/facade/StatusFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/response/StatusResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserStatusService.java
Labels: 기능 추가

#132 🔀 ::(#131) 수험표 엑셀 양식 올리기
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/excel/AdmissionTicket.java
Labels: chore

#138 🔀 :: 500을 띄우지 않기 위한 노력1 - excel 다운로드 IOException 핸들링
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/exception/ExcelOException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
Labels: chore

#139 🔀 :: (#135) Application User prefix 분리
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/ApplicationController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/ApplicationUserController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/aop/SubmitAspect.java
Labels: 리팩토링

#143 🔀 :: (#134) Application Study-Plan api 생성
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/ApplicationController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/response/QueryStudyPlanResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/QueryStudyPlanService.java
Labels: 기능 추가

#142 🔀 :: try 범위 수정 및 controller에 있는 IOException 삭제
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/AdminController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java
Labels: chore

#145 🔀 ::(#144) findById -> findByToken 수정
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/TokenRefreshService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/refresh_token/domain/repository/RefreshTokenRepository.java
Labels: 버그

#149 🔀 :: User 엔티티에 학교 전화번호 추가
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
Labels: 버그

#153 🔀 :: (#150) 토큰 발급 부분이 공통되는 부분이 많아 global로 분리하였습니다
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/AdminController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/LoginService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/TokenRefreshService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/response/TokenResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserLoginService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserSignupService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/jwt/JwtTokenProvider.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/util/TokenRefreshUtil.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/util/dto/TokenResponse.java
Labels: 리팩토링

#155 🔀 :: QueryDsl 오류 수정
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantsService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserInformationRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserInformationRepositoryImpl.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/QueryDslConfig.java
Labels: 리팩토링

#140 🔀 :: (#130) 비밀번호 변경
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/request/PasswordRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/ChangePasswordService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/VerifyAuthCodeService.java
Labels: 기능 추가
