Repository EntryDSM/Rolls-Royce, pull requests merged in 2022-08, with the labels that each got.

#401 🔀 :: (#400) head count 오류 해결 및 칼럼 추가
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/GetApplicantsRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/response/ApplicantsResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantsService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/request/ChangeTypeRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/response/QueryTypeResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
Labels: 버그, 기능 추가

#403 🔀 :: (#402) 파라미터가 9개인데 ?10을 호출해서 발생한 500 에러
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserRepository.java
Labels: 버그

#404 🔀 :: (#403) null이라면 query 조건 패스
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantsService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserRepository.java
Labels: 버그

#406 🔀 :: (#405) 유저 role 오류 수정 및 수정사항 반영
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/auth/AuthDetailsService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/jwt/JwtTokenProvider.java
Labels: 버그, chore

#408 🔀 :: (#407) Querydsl 설정
  build.gradle
  src/main/java/kr/hs/entrydsm/rollsroyce/global/config/QuerydslConfig.java
Labels: 기능 추가, 프로젝트 설정

#410 🔀 :: (#409) querydsl 적용
  build.gradle
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/GetApplicantsRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantsService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/ScoreCustomRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/ScoreCustomRepositoryImpl.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/ScoreRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserCustomRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserCustomRepositoryImpl.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/vo/ApplicantVo.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: chore, 리팩토링

#416 🔀 :: (#415) limit, offset, orderBy 설정 + pageable 변수명 통일
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserCustomRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserCustomRepositoryImpl.java
Labels: chore

#419 🔀 :: (#418) 필터링 버그 수정
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserCustomRepositoryImpl.java
Labels: 버그, chore

#420 🔀 :: (#418) in절로 수정
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserCustomRepositoryImpl.java
Labels: 버그, chore

#421 🔀 :: (#418) 페이징 처리 버그 해결
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserCustomRepositoryImpl.java
Labels: 버그, chore
