Repository EntryDSM/Rolls-Royce, pull requests merged in 2022-09, with the labels that each got.

#425 🔀 :: (#424) 변수명 수정
  .github/CODEOWNERS
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/GetApplicantsRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserCustomRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/repository/UserCustomRepositoryImpl.java
Labels: 버그, 리팩토링

#427 🔀 :: (#426) CORS Origins 수정
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/WebConfig.java
  src/main/resources/application.yml
Labels: chore

#428 🔀 :: (#426) CORS Origin 설정
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/WebConfig.java
  src/main/resources/application.yml
Labels: 버그, chore, 리팩토링

#430 🔀 :: (#413) 날짜 변경 제약 설정
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/exception/InvalidScheduleSequenceException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/presentation/dto/ScheduleDto.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/service/GetSchedulesService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/service/UpdateSchedulesService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
Labels: chore

#432 🔀 :: (#431) 엑셀생성 new
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/ExcelController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/excel/NewApplicantInformation.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/NewApplicantsExcelService.java
Labels: 기능 추가

#438 🔀 :: (#437) educationalStatus 필드 추가
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/response/StatusResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserStatusService.java
Labels: 리팩토링
