Repository EntryDSM/Rolls-Royce, pull requests merged in 2022-05, with the labels that each got.

#340 🔀 :: (#339) 로그인 예외 처리
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserLoginService.java
Labels: 리팩토링

#342 🔀 :: (#341) 유저 정보 변경 학번 검증
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/request/ChangeGraduationInformationRequest.java
Labels: 버그

#345 🔀 :: (#344) 전형 구분 선택 시 졸업일 날짜 제한
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/exception/InvalidGraduateAtException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeTypeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
Labels: chore

#347 🔀 :: (#346) 인증 번호 발송 Api에서 ttl 설정 수정
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java
Labels: chore, 리팩토링

#349 🔀 :: (#348) 졸업자, 검정고시 졸업연도 입력 오류 400
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/request/ChangeTypeRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/ChangeTypeService.java
Labels: 버그

#353 🔀 :: (#336) 지원자 목록 엑셀
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java
Labels: 기능 추가

#352 🔀 :: (#351) Code Owners 추가
  .github/CODEOWNERS
Labels: DOCS

#361 🔀 :: (#359) 지원자 목록 QueryString 400 오류
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/GetApplicantsRequest.java
Labels: 버그

#363 🔀 :: (#362) User Sex NPE
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/presentation/dto/request/ChangeInformationRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
Labels: 버그

#365 🔀 :: (#364) 엑셀 값 OOB
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java
Labels: 버그

#367 🔀 :: (#366) 지원자 세부 정보 Response 수정
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/response/ApplicantDetailsResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantDetailsService.java
Labels: chore, 리팩토링

#371 🔀 :: (#369) 지원자 목록 엑셀 '공란' -> '-'
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java
Labels: chore

#372 🔀 :: (#370) 지원자 목록 엑셀 성적 출력 버그 수정 및 'x' -> '-'
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java
Labels: 버그

#375 🔀 :: (#374) 지원자 정보 가져오기 NPE 해결
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/GetApplicantDetailsService.java
Labels: 버그

#373 🔀 :: (#368) 비밀번호 재설정 이메일 템플릿 설정
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendEmailAuthCodeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendPasswordAuthCodeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/ses/SESUtil.java
Labels: 리팩토링

#378 🔀 :: (#377) 이메일 전송 안됨
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/AuthCodeLimit.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/types/Action.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendEmailAuthCodeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendPasswordAuthCodeService.java
Labels: 버그, chore
