Repository EntryDSM/Rolls-Royce, pull requests merged in 2022-07, with the labels that each got.

#393 🔀 :: (#392) 토큰 버그
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserSignupService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/jwt/JwtTokenProvider.java
Labels: 버그

#391 🔀 :: (#390) PDF 설정
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/ApplicationPdfGenerator.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/TemplateFileName.java
Labels: chore

#395 🔀 :: (#382) 사회통합전형에 보호대상 아동 추가
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/User.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/types/ApplicationRemark.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pdf/PdfDataConverter.java
Labels: 기능 추가, chore

#396 🔀 :: (#383) 봉사시간 수정
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/ApplicationCase.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/GraduationCase.java
Labels: 기능 추가, chore
