Repository EntryDSM/Rolls-Royce, pull requests merged in 2022-04, with the labels that each got.

#333 🔀 :: (#332) 어드민 토큰 role/"admin" -> enum값으로 변경
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/LoginService.java
Labels: 버그

#335 🔀 :: (#334) url 규칙 통일시키기
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/schedule/presentation/ScheduleController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
Labels: chore

#337 🔀 :: (#331) 이메일 전송 안되는 버그
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/domain/AuthCode.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/facade/UserAuthCodeFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendEmailAuthCodeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/SendPasswordAuthCodeService.java
Labels: 버그, 리팩토링
