Repository EntryDSM/Rolls-Royce, pull requests merged in 2023-05, with the labels that each got.

#510 🔀 :: (#509) 지원정보 생성 시 status 생성
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/entryinfo/service/CreateEntryInfoService.java
Labels: 기능 추가

#505 🔀 : (#499) 질문 상세조회 API 구현
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/exception/AccessDeniedQnaException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/exception/ReplyNotFoundException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/dto/response/QueryDetailsQnaResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/dto/response/QueryQnaResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/QueryDetailsQnaService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/QueryQnaService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
Labels: 기능 추가

#495 🔀 :: (#481) Pass API 구현
  build.gradle
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/domain/PassInfo.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/domain/repository/PassInfoRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/exception/InvalidOkCertConnectException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/exception/InvalidPassException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/exception/PassInfoNotFoundException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/presentation/PassController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/presentation/PassPopupController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/presentation/dto/response/QueryPassInfoResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/service/QueryPassInfoService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/dto/request/SignupRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/UserSignupService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pass/PassUtil.java
  src/main/resources/application.yml
  src/main/webapp/WEB-INF/lib/OkCert3-java1.5-2.3.1.jar
  src/main/webapp/WEB-INF/view/phone_popup2.jsp
Labels: 기능 추가

#507 🔀 :: (#506) Access Denied Error 해결
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/UploadPhotoService.java
Labels: 버그

#525 🔀 :: (#524) response 값 수정
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/domain/repository/ReplyRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/dto/response/QueryDetailsQnaResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/QueryDetailsQnaService.java
Labels: chore, 리팩토링

#514 🔀 :: (#513) 공지사항 전체조회 API 구현
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/domain/repository/NoticeRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/presentation/NoticeController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/presentation/dto/request/CreateNoticeRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/presentation/dto/response/.gitkeep
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/presentation/dto/response/QueryNoticeResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/service/QueryNoticeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
Labels: 기능 추가

#527 🔀 :: (#526) 1, 2차 합격 여부 조회 API
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/pass/exception/AdmissionUnavailableException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/pass/presentation/IsPassedController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/pass/presentation/dto/response/QueryIsFirstRoundPassResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/pass/presentation/dto/response/QueryIsSecondRoundPassResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/pass/service/QueryIsFirstRoundPassService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/pass/service/QueryIsSecondRoundPassService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/status/domain/Status.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
Labels: 기능 추가

#520 🔀 :: (#515) 내 질문 조회 API 구현
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/domain/repository/QnaRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/facade/QnaFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/QnaController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/QueryMyQnaService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
Labels: 기능 추가

#542 🔀 :: (#536) 배너링크 업로드 API
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/domain/BannerLink.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/domain/repository/BannerLinkRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/presentation/BannerLinkController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/service/UploadBannerLinkService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/exception/BannerLinkNotFoundException.java
Labels: 기능 추가

#538 🔀 :: (#537) 객체 생성 문제 해결
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/s3/S3Util.java
Labels: 버그

#546 🔀 :: (#545) 배너 생성 API 구현
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/domain/BannerLink.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/presentation/BannerLinkController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/service/CreateBannerLinkService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
Labels: 기능 추가

#533 🔀 :: (#531) 전형요강 수정 API 구현
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/domain/Screen.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/exception/ScreenNotFoundException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/presentation/ScreenController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/presentation/dto/request/UpdateScreenRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/service/UpdateScreenService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
Labels: 리팩토링

#530 🔀 :: (529) Faq CRUD API
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/domain/Faq.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/domain/repository/FaqRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/domain/type/FaqType.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/exception/FaqNotFoundException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/presentation/FaqController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/presentation/dto/request/CreateFaqRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/presentation/dto/request/UpdateFaqRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/presentation/dto/response/QueryFaqInfoResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/presentation/dto/response/QueryFaqResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/service/CreateFaqService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/service/DeleteFaqService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/service/QueryFaqInfoService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/service/QueryFaqListByTypeService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/service/QueryFaqListService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/faq/service/UpdateFaqService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
Labels: 기능 추가
