Repository EntryDSM/Rolls-Royce, pull requests merged in 2023-06, with the labels that each got.

#544 🔀 :: (#543) 배너 조회 API 구현
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/presentation/BannerLinkController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/presentation/dto/response/QueryBannerLinkListResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/banner/service/QueryBannerLinkListService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
Labels: 기능 추가

#551 🔀 :: (#549) Pass 팝업 HTML로 변환
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/presentation/PassController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/presentation/PassPopupController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/service/PassPopupService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
  src/main/webapp/WEB-INF/view/phone_popup2.jsp
Labels: 버그

#558 🔀 :: (#557) 패스 인증 리다이렉트 url 설정 추가
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/exception/InvalidUrlException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/presentation/PassController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/presentation/dto/request/PassPopupRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/presentation/dto/response/QueryPassInfoResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/service/PassPopupService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/auth/service/QueryPassInfoService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/presentation/UserController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/user/service/ChangePasswordService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/pass/RedirectUrlChecker.java
  src/main/resources/application.yml
Labels: 기능 추가

#561 🔀 :: (#506) 도메인 추가
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/WebConfig.java
  src/main/resources/application.yml
Labels: chore

#563 🔀 :: (#553) 공지사항 사진 업로드 api 구현
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/presentation/NoticeController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/service/UploadNoticeImageService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/s3/S3Util.java
Labels: 기능 추가
