Repository EntryDSM/Rolls-Royce, pull requests merged in 2023-04, with the labels that each got.

#480 🔀 :: (#479) BaseTimeEntity 설정
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/domain/Reply.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/domain/Qna.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/entity/QnaTimeEntity.java
Labels: 리팩토링

#489 🔀 :: (#488) S3에 폴더 경로 추가
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/service/UploadPhotoService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/utils/s3/S3Util.java
Labels: 기능 추가

#497 🔀 :: (#496) 코드 전체적인 사소한 수정
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/CreateReplyService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/domain/Notice.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/domain/Qna.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
Labels: chore

#494 🔀 :: (#493) 질문 전체 조회 API 구현
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/domain/Qna.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/domain/repository/QnaRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/QnaController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/dto/response/.gitkeep
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/dto/response/QueryQnaResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/QueryQnaService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/security/SecurityConfig.java
Labels: 기능 추가

#501 🔀 :: (#500) 데이터 반환 에러 해결
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/domain/Qna.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/QueryQnaService.java
Labels: 버그

#498 🔀 :: (#492) 공지사항 수정 API 구현
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/domain/Notice.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/presentation/NoticeController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/presentation/dto/request/UpdateNoticeRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/notice/service/UpdateNoticeService.java
Labels: 기능 추가

#504 🔀 :: (#503) gradle build action으로 변경
  .github/workflows/CD.yml
Labels: 버그

#465 🔀 :: (#464) 질문 삭제 API 구현
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/AdminController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/DeleteQnaAdminService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/exception/NotModifyQnaException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/exception/QnaWriterMisMatchedException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/QnaController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/CreateQnaService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/DeleteQnaService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/UpdateQnaService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
Labels: 기능 추가

#491 🔀 :: (#490) 전형요강 생성 API 구현
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/domain/Screen.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/domain/repository/ScreenRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/exception/.gitkeep
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/presentation/ScreenController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/presentation/dto/request/CreateScreenRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/presentation/dto/response/.gitkeep
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/screen/service/CreateScreenService.java
Labels: 기능 추가
