Repository EntryDSM/Rolls-Royce, pull requests merged in 2023-03, with the labels that each got.

#460 🔀 :: (#459) ddl auto update -> create로 변경
  src/main/resources/application.yml
Labels: 리팩토링

#449 🔀 :: 엑셀 출력 json 형식으로 변환
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/exception/InvalidFormatException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/ExcelController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/AdmissionTicketRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/PrintApplicantsRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/response/AdmissionTicketResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/response/PrintApplicantsResponse.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/AdmissionTicketExcelService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/AdmissionTicketService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/ApplicantsExcelService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/NewApplicantsExcelService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/PrintApplicantsService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/application/domain/repository/GraduationRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/entryinfo/domain/repository/EntryInfoCustomRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/entryinfo/domain/repository/EntryInfoCustomRepositoryImpl.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/entryinfo/domain/repository/vo/AdmissionTicketVo.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/entryinfo/domain/repository/vo/NewApplicantVo.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/school/domain/repository/SchoolRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/GraduationCaseCustomRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/GraduationCaseCustomRepositoryImpl.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/GraduationCaseRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/ScoreCustomRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/ScoreCustomRepositoryImpl.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/vo/GraduationCaseVo.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/score/domain/repository/vo/ScoreVo.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
Labels: 리팩토링

#456 🔀 :: (#455) 질문 수정 API 구현
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/domain/Qna.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/exception/.gitkeep
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/exception/NotModifyQnaException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/exception/QnaNotFoundException.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/facade/.gitkeep
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/facade/QnaFacade.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/QnaController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/dto/request/UpdateQnaRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/UpdateQnaService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/global/error/exception/ErrorCode.java
Labels: 기능 추가

#463 🔀 :: (#462) 답변 생성 API 구현
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/domain/Reply.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/domain/repository/ReplyRepository.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/AdminController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/CreateReplyRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/CreateReplyService.java
Labels: 기능 추가

#476 🔀 :: (#475) 오타 수정
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/QnaController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/dto/request/CreateQnaRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/dto/request/UpdateQnaRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/CreateQnaService.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/UpdateQnaService.java
Labels: chore

#478 🔀 :: (#477) isReplied 삭제
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/presentation/dto/request/CreateQnaRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/qna/service/CreateQnaService.java
Labels: chore

#469 🔀 :: (#468) 답변 수정 API 구현
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/domain/Reply.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/AdminController.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/presentation/dto/request/UpdateReplyRequest.java
  src/main/java/kr/hs/entrydsm/rollsroyce/domain/admin/service/UpdateReplyService.java
Labels: 기능 추가
